import type { WidgetTemplate } from "@/types/widgets";
import {
  Droplets,
  Flame,
  Target,
  Scale,
  Heart,
  Moon,
  Activity,
  Coffee,
  Smile,
  Notebook,
  Brain,
  Sparkles,
  Wind,
  Move,
  Quote,
  Smartphone,
  Gauge,
  CheckSquare,
  CalendarClock,
  Pill,
  ShieldOff,
  ClipboardList,
  DollarSign,
  Brush,
  Hammer,
  Wrench,
  ListChecks,
  Users,
  CalendarDays,
  Utensils,
  Wallet,
  ImageIcon,
  HeartPulse,
  Car,
  Cake,
  PartyPopper,
  Gift,
  Briefcase,
  Timer,
  PiggyBank,
  TrendingUp,
  Home as HomeIcon,
  Flag,
} from "lucide-react";

export const widgetTemplates: WidgetTemplate[] = [
  {
    id: "water",
    name: "Water Intake",
    description: "Track daily water consumption",
    icon: Droplets,
    category: "health",
    color: "blue",
    defaultTarget: 8,
    unit: "cups",
    units: ["cups","ml","oz"],
  },
  {
    id: "calories",
    name: "Calories Burned",
    description: "Monitor daily calorie expenditure",
    icon: Flame,
    category: "health",
    color: "orange",
    defaultTarget: 2500,
    unit: "cal",
    units: ["cal"]
  },
  {
    id: "steps",
    name: "Daily Steps",
    description: "Count your steps throughout the day",
    icon: Target,
    category: "health",
    color: "green",
    defaultTarget: 10000,
    unit: "steps",
    units: ["steps"]
  },
  {
    id: "weight",
    name: "Weight Tracking",
    description: "Monitor weight changes over time",
    icon: Scale,
    category: "health",
    color: "purple",
    defaultTarget: 150,
    unit: "lbs",
    units: ["lbs","kg"]
  },
  {
    id: "heartrate",
    name: "Heart Rate",
    description: "Track resting heart rate",
    icon: Heart,
    category: "health",
    color: "pink",
    defaultTarget: 70,
    unit: "bpm",
    units: ["bpm"]
  },
  {
    id: "sleep",
    name: "Sleep Duration",
    description: "Monitor nightly sleep hours",
    icon: Moon,
    category: "health",
    color: "purple",
    defaultTarget: 8,
    unit: "hours",
    units: ["hours"]
  },
  {
    id: "exercise",
    name: "Exercise Tracker",
    description: "Track workouts, set weekly goals, and monitor fitness progress",
    icon: Activity,
    category: "health",
    color: "green",
    defaultTarget: 3,
    unit: "workouts",
    units: ["workouts"]
  },
  {
    id: "caffeine",
    name: "Caffeine Intake",
    description: "Monitor daily caffeine consumption",
    icon: Coffee,
    category: "health",
    color: "gold",
    defaultTarget: 2,
    unit: "cups",
    units: ["cups"]
  },
  {
    id: "nutrition",
    name: "Daily Nutrition",
    description: "Track your daily meals and nutrition intake with breakfast, lunch, dinner, and snacks",
    icon: Utensils,
    category: "health",
    color: "green",
    defaultTarget: 1,
    unit: "meals",
    units: ["meals"]
  },
  {
    id: "mood",
    name: "Mood Tracker",
    description: "Log how you feel each day",
    icon: Smile,
    category: "wellness",
    color: "teal",
    defaultTarget: 1,
    unit: "entry",
    units: ["entry"]
  },
  {
    id: "journal",
    name: "Daily Journal",
    description: "Capture your thoughts and reflections",
    icon: Notebook,
    category: "wellness",
    color: "pink",
    defaultTarget: 1,
    unit: "entry",
    units: ["entry"]
  },
  {
    id: "meditation",
    name: "Meditation Minutes",
    description: "Track daily meditation time",
    icon: Brain,
    category: "wellness",
    color: "blue",
    defaultTarget: 10,
    unit: "min",
    units: ["min"]
  },
  {
    id: "gratitude",
    name: "Gratitude Journal",
    description: "Note what you're thankful for",
    icon: Sparkles,
    category: "wellness",
    color: "gold",
    defaultTarget: 1,
    unit: "entry",
    units: ["entry"]
  },
  {
    id: "breathwork",
    name: "Breathwork Timer",
    description: "Guided 4-7-8 breathing sessions",
    icon: Wind,
    category: "wellness",
    color: "blue",
    defaultTarget: 5,
    unit: "min",
    units: ["min"]
  },
  {
    id: "stretch",
    name: "Stretch Breaks",
    description: "Reminders to move and stretch",
    icon: Move,
    category: "wellness",
    color: "green",
    defaultTarget: 3,
    unit: "breaks",
    units: ["breaks"]
  },
  {
    id: "affirmations",
    name: "Daily Affirmations",
    description: "Positive affirmation carousel",
    icon: Quote,
    category: "wellness",
    color: "purple",
    defaultTarget: 1,
    unit: "set",
    units: ["set"]
  },
  {
    id: "screen_time",
    name: "Screen-Time Log",
    description: "Track non-work screen minutes",
    icon: Smartphone,
    category: "wellness",
    color: "gold",
    defaultTarget: 60,
    unit: "min",
    units: ["min"]
  },
  {
    id: "stress",
    name: "Stress Check-in",
    description: "1-10 scale quick log",
    icon: Gauge,
    category: "wellness",
    color: "pink",
    defaultTarget: 1,
    unit: "entry",
    units: ["entry"]
  },
  {
    id: "self_care",
    name: "Self-Care Checklist",
    description: "Custom daily self-care items",
    icon: CheckSquare,
    category: "wellness",
    color: "green",
    defaultTarget: 1,
    unit: "list",
    units: ["list"]
  },
  {
    id: "habit_tracker",
    name: "Habit Tracker",
    description: "Build daily habits with streak tracking and milestones",
    icon: Target,
    category: "wellness",
    color: "purple",
    defaultTarget: 1,
    unit: "day",
    units: ["day"]
  },
  {
    id: "doctor_appt",
    name: "Doctor Appointments",
    description: "Upcoming medical visits and reminders",
    icon: CalendarClock,
    category: "medical",
    color: "purple",
    defaultTarget: 1,
    unit: "event",
    units: ["event"]
  },
  {
    id: "medication",
    name: "Medication Tracker",
    description: "Track doses and refill reminders",
    icon: Pill,
    category: "medical",
    color: "pink",
    defaultTarget: 1,
    unit: "dose",
    units: ["dose"]
  },
  {
    id: "quit_habit",
    name: "Habit You're Quitting",
    description: "Track progress and milestones for breaking bad habits",
    icon: ShieldOff,
    category: "medical",
    color: "slate",
    defaultTarget: 1,
    unit: "day",
    units: ["day"]
  },
  {
    id: "symptom_log",
    name: "Symptom Diary",
    description: "Record symptoms for consultations",
    icon: ClipboardList,
    category: "medical",
    color: "orange",
    defaultTarget: 1,
    unit: "entry",
    units: ["entry"]
  },
  {
    id: "medical_bills",
    name: "Medical Bills",
    description: "Track upcoming medical payments",
    icon: DollarSign,
    category: "medical",
    color: "slate",
    defaultTarget: 1,
    unit: "bill",
    units: ["bill"]
  },
  {
    id: "chores",
    name: "Chores Checklist",
    description: "Daily and weekly household chores",
    icon: ListChecks,
    category: "household",
    color: "gold",
    defaultTarget: 1,
    unit: "list",
    units: ["list"]
  },
  {
    id: "home_projects",
    name: "Home Projects",
    description: "DIY and improvement tasks",
    icon: Hammer,
    category: "household",
    color: "blue",
    defaultTarget: 1,
    unit: "project",
    units: ["project"]
  },
  {
    id: "maintenance",
    name: "Maintenance Schedule",
    description: "Filter changes, inspections, etc.",
    icon: Wrench,
    category: "household",
    color: "green",
    defaultTarget: 1,
    unit: "task",
    units: ["task"]
  },
  {
    id: "cleaning",
    name: "Deep Cleaning",
    description: "Monthly thorough cleaning tasks",
    icon: Brush,
    category: "household",
    color: "purple",
    defaultTarget: 1,
    unit: "task",
    units: ["task"]
  },
  {
    id: "family_members",
    name: "Family Members",
    description: "Roster with contact info & birthdays",
    icon: Users,
    category: "family",
    color: "purple",
    defaultTarget: 1,
    unit: "list",
    units: ["list"]
  },
  {
    id: "family_calendar",
    name: "Family Calendar",
    description: "Shared events & birthdays",
    icon: CalendarDays,
    category: "family",
    color: "blue",
    defaultTarget: 1,
    unit: "event",
    units: ["event"]
  },
  {
    id: "family_chores",
    name: "Chore Assignments",
    description: "Who is responsible today",
    icon: ClipboardList,
    category: "family",
    color: "green",
    defaultTarget: 1,
    unit: "task",
    units: ["task"]
  },
  {
    id: "meal_plan",
    name: "Meal Plan",
    description: "Weekly dinner plan & groceries",
    icon: Utensils,
    category: "family",
    color: "gold",
    defaultTarget: 1,
    unit: "week",
    units: ["week"]
  },
  {
    id: "family_budget",
    name: "Allowance / Budget",
    description: "Track allowances & shared expenses",
    icon: Wallet,
    category: "family",
    color: "purple",
    defaultTarget: 1,
    unit: "budget",
    units: ["budget"]
  },
  {
    id: "photo_carousel",
    name: "Photo Carousel",
    description: "Recent family memories",
    icon: ImageIcon,
    category: "family",
    color: "pink",
    defaultTarget: 1,
    unit: "photo",
    units: ["photo"]
  },
  {
    id: "emergency_info",
    name: "Health & Emergency Info",
    description: "Allergies, contacts, insurance",
    icon: HeartPulse,
    category: "family",
    color: "pink",
    defaultTarget: 1,
    unit: "entry",
    units: ["entry"]
  },
  {
    id: "carpool",
    name: "Carpool Schedule",
    description: "Who's driving where & when",
    icon: Car,
    category: "family",
    color: "blue",
    defaultTarget: 1,
    unit: "ride",
    units: ["ride"]
  },
  {
    id: "birthdays",
    name: "Birthdays",
    description: "Upcoming birthdays",
    icon: Cake,
    category: "social",
    color: "pink",
    defaultTarget: 1,
    unit: "birthday",
    units: ["birthday"]
  },
  {
    id: "social_events",
    name: "Events",
    description: "Concerts, meetups, parties",
    icon: PartyPopper,
    category: "social",
    color: "purple",
    defaultTarget: 1,
    unit: "event",
    units: ["event"]
  },
  {
    id: "holidays",
    name: "Holidays",
    description: "Public and personal holidays",
    icon: Gift,
    category: "social",
    color: "green",
    defaultTarget: 1,
    unit: "holiday",
    units: ["holiday"]
  },
  {
    id: "work_projects",
    name: "Projects Dashboard",
    description: "Status of active projects",
    icon: Briefcase,
    category: "work",
    color: "blue",
    defaultTarget: 1,
    unit: "project",
    units: ["project"]
  },
  {
    id: "work_deadlines",
    name: "Deadlines",
    description: "Upcoming milestones & due dates",
    icon: CalendarClock,
    category: "work",
    color: "orange",
    defaultTarget: 1,
    unit: "deadline",
    units: ["deadline"]
  },
  {
    id: "pomodoro",
    name: "Pomodoro Timer",
    description: "25-minute focus sessions",
    icon: Timer,
    category: "work",
    color: "teal",
    defaultTarget: 1,
    unit: "session",
    units: ["session"]
  },
  {
    id: "finance_budget",
    name: "Budget Planner",
    description: "Track monthly budget vs spend",
    icon: Wallet,
    category: "finance",
    color: "green",
    defaultTarget: 1,
    unit: "budget",
    units: ["budget"]
  },
  {
    id: "savings_tracker",
    name: "Savings Tracker",
    description: "Monitor savings progress",
    icon: PiggyBank,
    category: "finance",
    color: "green",
    defaultTarget: 1,
    unit: "amount",
    units: ["amount"]
  },
  {
    id: "net_worth",
    name: "Net Worth",
    description: "Assets minus liabilities snapshot",
    icon: TrendingUp,
    category: "finance",
    color: "purple",
    defaultTarget: 1,
    unit: "amount",
    units: ["amount"]
  },
  {
    id: "properties",
    name: "Properties",
    description: "Track real-estate assets",
    icon: HomeIcon,
    category: "finance",
    color: "gold",
    defaultTarget: 1,
    unit: "property",
    units: ["property"]
  },
  {
    id: "financial_goals",
    name: "Financial Goals",
    description: "Milestones toward big purchases",
    icon: Flag,
    category: "finance",
    color: "pink",
    defaultTarget: 1,
    unit: "goal",
    units: ["goal"]
  }
];
